### ISSUE TITLE
Support Light theme

### ISSUE THREAD

**Issue by dtantono** [ArthurHeitmann/photon-reddit#6]
Hi
the design is great. But, I think not everyone like dark theme. is it possible to support light theme?

**Comment by ArthurHeitmann** [comment]
Changing most of the colors would be relatively simple, since they are mostly just CSS variables. The main challenge are all the icons. For them all colors are hardcoded. Since they are SVGs it could be possible to dynamically change the color by editing the XML contents, but that would take a bit of work. I'll think a bit how that could be solved.

**Comment by ArthurHeitmann** [comment]
I've now added a light theme. I'm no UI designer, so if someone has suggestion on what can be improved, I'm open.

Screenshot:
![image](https://github.com/ArthurHeitmann/photon-reddit/assets/37270165/dada9425-739e-4774-9b58-ec1936e5f8d2)
